services:
  #python flash application service
  app:
    #build image from the dockerfile in the current directory
    build: .
    container_name: translator_app
    #map port 5000 on the host to port 5000 in the container
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - huggingface-cache:/home/appuser/.cache/huggingface

  #the redis service
  redis:
    image: "redis:alpine"
    container_name: redis_cache
    #exposes redis port (optional, but useful for debugging with a local client)
    ports:
      - "6379:6379"
    #persists redis data across container restarts
    volumes:
      - redis_data:/data

#define a named volume for redis data persistence
volumes:
  redis_data:
  huggingface-cache: